services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    networks:
      - appnet

  redis:
    image: redis:7.0.0
    ports:
      - "6380:6379"

    networks:
      - appnet

networks:
  appnet:
    driver: bridge
